spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: mscourse
      password: mscourse

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false