spring:
  application:
    name: clientservice

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://mscourse:mscourse@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


