spring:
  application:
    name: evaluatorservice
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://mscourse:mscourse@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes